### ISSUE TITLE
Support for focus and theater mode

### ISSUE THREAD

**Issue by filipebranth** [thieleju/chess-com-insights#181]
I only wish it would work on focus mode, and in the theater mode as well... That's about it, I love the extension as it helps a lot in detecting cheaters and preventing unnecessary frustration, it works perfectly for me besides that.

**Comment by thieleju** [comment]
Great idea, I'll add support for focus and theater mode in january

**Comment by thieleju** [comment]
Added support for theatre and focus mode, update will be live in about 12 hours after it has been reviewed by google.

Please let me know if you encounter any issues :)

Added in https://github.com/thieleju/chess-com-insights/commit/4144f328ab0579a13aa47beff029d7e12db20c18
