### ISSUE TITLE
EROR

### ISSUE THREAD

**Issue by MuajAmin** [thieleju/chess-com-insights#43]
BRO extension not work and not install

**Comment by thieleju** [comment]
Hi, can you describe what exactly is not working and which browser you're using? 

Did you try to install the extension from the chrome web store? ([this link](https://chrome.google.com/webstore/detail/chesscom-insights/mobpnhbkmljienoleojnhbfhkhodpffe))

**Comment by thieleju** [comment]
Closing this because of insufficient error description

**Comment by maxiwolleb** [comment]
No work bro
